export const env = {
    PRIVATE_WALLET_KEY: '',
    IMXURL: 'https://api.x.immutable.com/v1',
    STARK: '0x5FDCCA53617f4d2b9134B29090C87D01058e27e9',
    REGISTRATION: '0x72a06bf2a1CE5e39cBA06c0CAb824960B587d64c',
    NETWORK: 'mainnet',
    API_KEY_INFURA: '',
    API_KEY_ALCHEMY: '',
    API_KEY_ETHERSCAN: '',
    DISCORD_WEBHOOK:'',
    JSON_CARDS_PATH: './cards_example.json'
}

export const vars = {
    MAX_TIME: 1000,//MAX_TIME_FROM_LAST_TRADE_ACCEPTED
    MIN_AMOUNT_TRADE: 50,//MIN_AMOUNT_TRADE_IN_LAsT_24h
    X_VAL: 0.000001,//DIFFERENCE_FROM_LOWEST_PRICE
    N_DIV: 10, //LIMIT_BUY
    CRESTA:10, //A SIMPLE, BASIC, MINIMUM CRESTA,
    LIST_SIZE:8,//HOW MANY ORDER CHECK EVERY LOOP
    SET_TIMEOUT:5000,//TIME WAIT BEFORE START NEW LOOP (IN MILLISECOND),
    DEBUG: false //ENABLE_DEBUG_LOG
}
