export const env = {
    PRIVATE_WALLET_KEY: '',
    IMXURL: 'https://api.x.immutable.com/v1',
    STARK: '0x5FDCCA53617f4d2b9134B29090C87D01058e27e9',
    REGISTRATION: '0x72a06bf2a1CE5e39cBA06c0CAb824960B587d64c',

    NETWORK: 'mainnet',
    API_KEY_INFURA: '',
    API_KEY_ALCHEMY: '',
    API_KEY_ETHERSCAN: '',
    DISCORD_WEBHOOK:'',

    JSON_CARDS_PATH: './cards.json'
}

export const vars = {
    MAX_TIME: 30,//MAX_TIME_FROM_LAST_TRADE_ACCEPTED
    MIN_AMOUNT_TRADE: 90,//MIN_AMOUNT_TRADE_IN_LAsT_24h
    X_VAL: 0.0000025,//DIFFERENCE_FROM_LOWEST_PRICE
    N_DIV: 10,//LIMIT_BUY
    CRESTA:5,//A SIMPLE, BASIC, MINIMUM CRESTA,
    LIST_SIZE:12,//HOW MANY ORDER CHECK EVERY LOOP
    SET_TIMEOUT:2000,//TIME WAIT BEFORE START NEW LOOP (IN MILLISECOND)
    DEBUG: false, //ENABLE_DEBUG_LOG
    HB_RATE:300, //SEND_HEARTBEAT_EVERY_N_LOOP_ITERATION
    BOT_NAME:'digital_bot',
    CHECK_BAL:false //check balance every loop then send msg
}
